/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4940aa3c-8120-4a05-a17b-15b863e88ec1",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_wSsPPtgfE",
    "aws_user_pools_web_client_id": "3lb1u06ki0ekg1kmba1da8m9ji",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://b4foceuhpvhylhbidvnsapkiky.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-6u4jmmywufg5xiyzj5dbrmfev4",
    "aws_cloud_logic_custom": [
        {
            "name": "MAPSFrontEndAPI",
            "endpoint": "https://4j3xv1gp95.execute-api.us-west-2.amazonaws.com/prod",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
